#!usr/bin/env bash
# client configuration with ssh

Host *
	PasswordAuthentication no
	IdentityFile ~/.ssh/school
	SendEnv LANG LC_*
	HashknownHosts yes
	GSSAPIAuthentication yes
	GSSAPIDelegateCredentials no
